(() => {
  const instagramUrl = 'https://www.instagram.com/direct/t/andreyfabricio_';
  const instagramProfileUrl = 'https://www.instagram.com/andreyfabricio_/';
  const email = 'orcamento@andrey.systems'; // Operational contact email. Change here if the address is replaced later.
  const translations = {
    en: {
      navOpen:'Open menu',navClose:'Close menu',navHome:'Home',navFeatured:'ERP',navProjects:'Projects',navSolutions:'Solutions',navResults:'Results',navContact:'Contact',
      heroStatement:'Building digital solutions for real needs.',heroSpecialties:'Websites / Systems / Automation',exploreProjects:'Explore Projects',startProject:'Start a Project',emailCta:'Email',heroLocation:'Based in Brazil / Working globally',
      featuredEyebrow:'Featured Project',featuredText:'A real management system built to centralize operational records, material control, budgets, work orders and reports.',challengeLabel:'Challenge',solutionLabel:'Solution',featuresLabel:'Main Features',resultLabel:'Result',viewFullCase:'View Full Case',
      projectsEyebrow:'Selected Projects',projectsTitle:'Projects with visual or functional proof.',projectErpType:'Client Project / Management System',projectErpText:'A custom system for internal operations, inventory, work orders, budgets, users, permissions, reports and backup.',viewProject:'View Project',projectImppelType:'Website Project',projectImppelText:'A business website direction for presenting services, credibility and contact paths with a cleaner digital presence.',projectSalvosType:'Personal Product / In Development',projectSalvosText:'A product in development used as a SaaS, routine and digital experience lab.',statusReal:'Real project',statusDirection:'Visual direction',statusDevelopment:'In development',statusConcept:'Concept project',discussProject:'Discuss Project',viewContext:'View Context',requestSimilar:'Request Similar',previewImppelSite:'Services / Projects / Contact',gymPreviewTitle:'Gym Website',gymPreviewMeta:'Plans / Schedule / Trial',churchPreviewTitle:'Church Website',churchPreviewMeta:'Events / Ministries / Contact',constructionPreviewTitle:'Construction Business',constructionPreviewMeta:'Services / Portfolio / Quote',conceptType:'Website Concept',gymTitle:'Fitness / Gym Website',gymText:'A focused concept for classes, plans, schedules and lead capture.',churchTitle:'Church Website',churchText:'A community concept for events, ministries, agenda and communication.',constructionTitle:'Construction Business Website',constructionText:'A concept for technical services, proof of work and budget requests.',
      solutionsEyebrow:'Solutions',solutionsTitle:'What I can build.',solution1Title:'Business Websites',solution1Text:'Modern, responsive websites designed to communicate clearly and support business goals.',solution2Title:'Landing Pages',solution2Text:'Focused pages created to present an offer, guide attention and encourage action.',solution3Title:'Management Systems',solution3Text:'Custom tools designed to organize information, processes and daily operations.',solution4Title:'Portfolio Websites',solution4Text:'Professional digital spaces for individuals, creators and businesses.',solution5Title:'Automation',solution5Text:'Practical automations that reduce repetitive work and improve workflows.',solution6Title:'Custom Digital Products',solution6Text:'Solutions designed around the specific needs of each project.',
      workEyebrow:'How I Work',workTitle:'From problem to launch, in clear stages.',discoverTitle:'Discover',discoverText:'Understanding the business, the problem, the users, the current process and the desired outcome.',planTitle:'Plan',planText:'Defining scope, priorities, references, structure, risks and the simplest effective solution.',buildTitle:'Build',buildText:'Designing, developing and validating the project through clear and manageable stages.',launchTitle:'Launch',launchText:'Testing, refining, publishing and preparing the product for real use.',workPrev:'Previous step',workNext:'Next step',
      resultsEyebrow:'Built Outcomes',resultsTitle:'Concrete changes, without invented numbers.',erpBeforeAfter:'Manual records to centralized operation.',erpOutcome:'Before: disconnected controls. Change: modules for materials, inventory, work orders and reports. Result: a clearer operational flow.',resultSiteLabel:'IMPPEL Website',siteBeforeAfter:'Limited presence to organized presentation.',siteOutcome:'Before: scattered presentation. Change: service, proof and contact structure. Result: a clearer path for visitors.',resultMobileLabel:'Mobile Experience',mobileOutcomeTitle:'Desktop and mobile as one product.',mobileOutcome:'Before: layouts could lose rhythm on small screens. Change: responsive sections and stable controls. Result: readable use on mobile.',resultWorkflowLabel:'Structured Workflow',workflowOutcomeTitle:'Scattered information to structured flow.',workflowOutcome:'Before: problems were loose ideas. Change: screens, modules, actions and next steps. Result: work becomes easier to explain and build.',
      contactEyebrow:'Contact',contactTitle:'Have an idea or a problem to solve?',contactText:"Let's build something useful.",labelName:'Name',labelCompany:'Company',labelContact:'Email or phone',labelType:'Project type',labelProblem:'Main current problem',labelTimeline:'Desired timeline',placeholderContact:'Email, WhatsApp or phone',placeholderProblem:'What needs to become clearer, faster or more organized?',placeholderTimeline:'This month, next quarter, no fixed deadline...',formInstagram:'Start a Project',formEmail:'Send by email',optionBusiness:'Business Website',optionLanding:'Landing Page',optionSystem:'Management System',optionPortfolio:'Portfolio Website',optionAutomation:'Automation',optionCustom:'Custom Digital Product',footerLine:'Andrey Fabricio / Digital Builder / Based in Brazil',rights:'All rights reserved.',
      caseHeroText:'A real system built for internal operations: CRM, budgets, work orders, materials, inventory, finance, after-sales, permissions and backup.',caseBack:'Back to Home',caseChallengeTitle:'Challenge',caseChallengeText:'The operation needed one reliable place to follow customers, budgets, service orders, material movement and responsibilities.',caseSolutionTitle:'Solution',caseSolutionText:'The ERP organizes the daily flow into connected modules with user roles, operational exports and technical backup.',caseFeaturesTitle:'Main Features',caseFeaturesHeading:'CRM, budgets, work orders, materials, inventory, finance and backup.',caseFeatureCrm:'CRM',caseFeatureBudgets:'Budgets',caseFeatureOrders:'Work Orders',caseFeatureMaterials:'Material Control',caseFeatureInventory:'Inventory',caseFeatureFinance:'Finance',caseFeatureAfterSales:'Warranties and after-sales',caseFeaturePermissions:'Role permissions',caseFeatureBackup:'Backup and restoration',caseResultTitle:'Result',caseResultText:'The project became the main proof that Andrey Systems can turn an operational problem into a usable digital system.',caseCtaTitle:'Want a system or site with this level of care?',caseCtaText:'Send the project context and I will help define the simplest next step.'
    },
    pt: {
      navOpen:'Abrir menu',navClose:'Fechar menu',navHome:'Inicio',navFeatured:'ERP',navProjects:'Projetos',navSolutions:'Solucoes',navResults:'Resultados',navContact:'Contato',
      heroStatement:'Construindo solucoes digitais para necessidades reais.',heroSpecialties:'Sites / Sistemas / Automacao',exploreProjects:'Ver projetos',startProject:'Iniciar um projeto',emailCta:'E-mail',heroLocation:'Baseado no Brasil / Atendendo globalmente',
      featuredEyebrow:'Projeto em destaque',featuredText:'Um sistema real de gestao criado para centralizar registros operacionais, controle de materiais, orcamentos, ordens de servico e relatorios.',challengeLabel:'Desafio',solutionLabel:'Solucao',featuresLabel:'Principais recursos',resultLabel:'Resultado',viewFullCase:'Ver caso completo',
      projectsEyebrow:'Projetos selecionados',projectsTitle:'Projetos com prova visual ou funcional.',projectErpType:'Projeto real / Sistema de gestao',projectErpText:'Sistema personalizado para operacao interna, estoque, ordens de servico, orcamentos, usuarios, permissoes, relatorios e backup.',viewProject:'Ver projeto',projectImppelType:'Projeto de site',projectImppelText:'Direcao de site empresarial para apresentar servicos, credibilidade e caminhos de contato com uma presenca digital mais limpa.',projectSalvosType:'Produto proprio / Em desenvolvimento',projectSalvosText:'Produto em desenvolvimento usado como laboratorio de SaaS, rotina e experiencia digital.',statusReal:'Projeto real',statusDirection:'Direcao visual',statusDevelopment:'Em desenvolvimento',statusConcept:'Projeto conceito',discussProject:'Conversar sobre projeto',viewContext:'Ver contexto',requestSimilar:'Solicitar similar',previewImppelSite:'Servicos / Projetos / Contato',gymPreviewTitle:'Site para academia',gymPreviewMeta:'Planos / Horarios / Teste',churchPreviewTitle:'Site para igreja',churchPreviewMeta:'Eventos / Ministerios / Contato',constructionPreviewTitle:'Construtora',constructionPreviewMeta:'Servicos / Portfolio / Orcamento',conceptType:'Conceito de site',gymTitle:'Site para academia',gymText:'Conceito focado em aulas, planos, horarios e captacao de interessados.',churchTitle:'Site para igreja',churchText:'Conceito comunitario para eventos, ministerios, agenda e comunicacao.',constructionTitle:'Site para construtora ou prestadora',constructionText:'Conceito para servicos tecnicos, prova de trabalho e pedidos de orcamento.',
      solutionsEyebrow:'Solucoes',solutionsTitle:'O que posso construir.',solution1Title:'Sites empresariais',solution1Text:'Sites modernos e responsivos para comunicar com clareza e apoiar objetivos comerciais.',solution2Title:'Landing pages',solution2Text:'Paginas focadas para apresentar uma oferta, guiar a atencao e incentivar uma acao.',solution3Title:'Sistemas de gestao',solution3Text:'Ferramentas personalizadas para organizar informacoes, processos e rotinas operacionais.',solution4Title:'Portfolios digitais',solution4Text:'Espacos profissionais para pessoas, criadores e negocios.',solution5Title:'Automacao',solution5Text:'Automacoes praticas para reduzir trabalho repetitivo e melhorar fluxos.',solution6Title:'Produtos digitais sob medida',solution6Text:'Solucoes desenhadas em torno da necessidade especifica de cada projeto.',
      workEyebrow:'Como trabalho',workTitle:'Do problema ao lancamento, em etapas claras.',discoverTitle:'Descobrir',discoverText:'Entender o negocio, o problema, os usuarios, o processo atual e o resultado desejado.',planTitle:'Planejar',planText:'Definir escopo, prioridades, referencias, estrutura, riscos e a solucao mais simples e eficaz.',buildTitle:'Construir',buildText:'Projetar, desenvolver e validar o projeto por meio de etapas claras e controladas.',launchTitle:'Lancar',launchText:'Testar, refinar, publicar e preparar o produto para uso real.',workPrev:'Etapa anterior',workNext:'Proxima etapa',
      resultsEyebrow:'Resultados construidos',resultsTitle:'Mudancas concretas, sem numeros inventados.',erpBeforeAfter:'De registros manuais para operacao centralizada.',erpOutcome:'Antes: controles desconectados. Mudanca: modulos para materiais, estoque, ordens de servico e relatorios. Resultado: um fluxo operacional mais claro.',resultSiteLabel:'Site IMPPEL',siteBeforeAfter:'De presenca limitada para apresentacao organizada.',siteOutcome:'Antes: apresentacao espalhada. Mudanca: estrutura de servicos, prova e contato. Resultado: um caminho mais claro para visitantes.',resultMobileLabel:'Experiencia mobile',mobileOutcomeTitle:'Desktop e mobile como um unico produto.',mobileOutcome:'Antes: layouts podiam perder ritmo em telas pequenas. Mudanca: secoes responsivas e controles estaveis. Resultado: leitura melhor no celular.',resultWorkflowLabel:'Fluxo estruturado',workflowOutcomeTitle:'De informacao espalhada para fluxo estruturado.',workflowOutcome:'Antes: problemas eram ideias soltas. Mudanca: telas, modulos, acoes e proximos passos. Resultado: o trabalho fica mais facil de explicar e construir.',
      contactEyebrow:'Contato',contactTitle:'Tem uma ideia ou problema para resolver?',contactText:'Vamos construir algo util.',labelName:'Nome',labelCompany:'Empresa',labelContact:'E-mail ou telefone',labelType:'Tipo de projeto',labelProblem:'Principal problema atual',labelTimeline:'Prazo desejado',placeholderContact:'E-mail, WhatsApp ou telefone',placeholderProblem:'O que precisa ficar mais claro, rapido ou organizado?',placeholderTimeline:'Este mes, proximo trimestre, sem prazo fixo...',formInstagram:'Iniciar um projeto',formEmail:'Enviar por e-mail',optionBusiness:'Site empresarial',optionLanding:'Landing page',optionSystem:'Sistema de gestao',optionPortfolio:'Portfolio digital',optionAutomation:'Automacao',optionCustom:'Produto digital sob medida',footerLine:'Andrey Fabricio / Digital Builder / Baseado no Brasil',rights:'Todos os direitos reservados.',
      caseHeroText:'Sistema real criado para operacao interna: CRM, orcamentos, ordens de servico, materiais, estoque, financeiro, pos-venda, permissoes e backup.',caseBack:'Voltar para Home',caseChallengeTitle:'Desafio',caseChallengeText:'A operacao precisava de um lugar confiavel para acompanhar clientes, orcamentos, ordens de servico, movimentacao de materiais e responsabilidades.',caseSolutionTitle:'Solucao',caseSolutionText:'O ERP organiza a rotina em modulos conectados com perfis de usuario, exportacoes operacionais e backup tecnico.',caseFeaturesTitle:'Principais recursos',caseFeaturesHeading:'CRM, orcamentos, ordens de servico, materiais, estoque, financeiro e backup.',caseFeatureCrm:'CRM',caseFeatureBudgets:'Orcamentos',caseFeatureOrders:'Ordens de servico',caseFeatureMaterials:'Controle de materiais',caseFeatureInventory:'Estoque',caseFeatureFinance:'Financeiro',caseFeatureAfterSales:'Garantias e pos-venda',caseFeaturePermissions:'Permissoes por cargo',caseFeatureBackup:'Backup e restauracao',caseResultTitle:'Resultado',caseResultText:'O projeto virou a principal prova de que a Andrey Systems consegue transformar um problema operacional em um sistema digital utilizavel.',caseCtaTitle:'Quer um sistema ou site com esse nivel de cuidado?',caseCtaText:'Envie o contexto do projeto e eu ajudo a definir o proximo passo mais simples.'
    }
  };
  const caseTabs = {
    en:{challenge:['Operational information was scattered.','Important records lived across manual controls and disconnected routines, making it harder to follow work orders, material movement, budgets and internal responsibilities from one place.'],solution:['A real ERP for daily operations.','The system centralizes CRM, budgets, work orders, materials, stock, finance, warranties, role permissions and backup routines in one operational environment.'],features:['Main features built around real routines.','CRM, budgets, service orders, material control, inventory, finance, warranties, after-sales, permissions by role, backup and restoration.'],result:['Proof through a working product.','The ERP IMPPEL shows a complete operational system without promising invented financial metrics: the proof is the structure, screens and implemented flow.']},
    pt:{challenge:['Informacoes operacionais estavam espalhadas.','Registros importantes ficavam em controles manuais e rotinas desconectadas, dificultando acompanhar ordens de servico, materiais, orcamentos e responsabilidades em um unico lugar.'],solution:['Um ERP real para a rotina diaria.','O sistema centraliza CRM, orcamentos, ordens de servico, materiais, estoque, financeiro, garantias, permissoes por cargo e rotinas de backup em um ambiente operacional.'],features:['Principais recursos criados em torno da rotina real.','CRM, orcamentos, ordens de servico, controle de materiais, estoque, financeiro, garantias, pos-venda, permissoes por cargo, backup e restauracao.'],result:['Prova por produto funcionando.','O ERP IMPPEL mostra um sistema operacional completo sem prometer metricas financeiras inventadas: a prova esta na estrutura, nas telas e no fluxo implementado.']}
  };
  const state = { lang: localStorage.getItem('andrey-lang') || 'en' };
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  function t(key){ return (translations[state.lang] && translations[state.lang][key]) || translations.en[key] || key; }
  function applyLanguage(lang){ state.lang = translations[lang] ? lang : 'en'; localStorage.setItem('andrey-lang', state.lang); document.documentElement.lang = state.lang === 'pt' ? 'pt-BR' : 'en'; $$('[data-i18n]').forEach(el => { el.textContent = t(el.dataset.i18n); }); $$('[data-i18n-placeholder]').forEach(el => { el.placeholder = t(el.dataset.i18nPlaceholder); }); $$('[data-i18n-aria-label]').forEach(el => { el.setAttribute('aria-label', t(el.dataset.i18nAriaLabel)); }); $$('[data-lang-option]').forEach(btn => btn.classList.toggle('is-active', btn.dataset.langOption === state.lang)); renderCaseTab($('.tab-button.is-active')?.dataset.caseTab || 'challenge'); updateQuote(); }
  function renderCaseTab(tab){ const panel = $('[data-case-panel]'); if(!panel) return; const data = (caseTabs[state.lang] || caseTabs.en)[tab] || caseTabs[state.lang].challenge; panel.querySelector('h3').textContent = data[0]; panel.querySelector('p').textContent = data[1]; $$('[data-case-tab]').forEach(btn => { const active = btn.dataset.caseTab === tab; btn.classList.toggle('is-active', active); btn.setAttribute('aria-selected', String(active)); }); }
  function quoteMessage(){ const form = $('#quote'); if(!form) return ''; const data = new FormData(form); const pt = state.lang === 'pt'; const lines = pt ? ['Ola, Andrey! Quero conversar sobre um projeto.','','Nome: '+(data.get('nome')||''),'Empresa: '+(data.get('empresa')||''),'Contato: '+(data.get('contato')||''),'Tipo de projeto: '+(data.get('tipo')||''),'Problema atual: '+(data.get('problema')||''),'Prazo desejado: '+(data.get('prazo')||''),'','Vi seu site da Andrey Systems e gostaria de um direcionamento.'] : ['Hi, Andrey! I want to talk about a project.','','Name: '+(data.get('nome')||''),'Company: '+(data.get('empresa')||''),'Contact: '+(data.get('contato')||''),'Project type: '+(data.get('tipo')||''),'Current problem: '+(data.get('problema')||''),'Desired timeline: '+(data.get('prazo')||''),'','I saw your Andrey Systems website and would like some direction.']; return lines.join('\\n'); }
  function updateQuote(){ const form = $('#quote'); if(!form) return; const message = quoteMessage(); const link = $('#quoteEmailLink'); if(link){ const subject = state.lang === 'pt' ? 'Solicitacao de projeto - Andrey Systems' : 'Project request - Andrey Systems'; link.href = 'mailto:' + email + '?subject=' + encodeURIComponent(subject) + '&body=' + encodeURIComponent(message); } }
  function initForm(){ const form = $('#quote'); if(!form) return; form.addEventListener('input', updateQuote); form.addEventListener('change', updateQuote); form.addEventListener('submit', (ev) => { ev.preventDefault(); updateQuote(); window.open(instagramUrl, '_blank', 'noopener,noreferrer') || window.open(instagramProfileUrl, '_blank', 'noopener,noreferrer'); }); updateQuote(); }
  function initNav(){ const header = $('[data-header]'); const toggle = $('.nav-toggle'); const nav = $('.site-nav'); toggle?.addEventListener('click', () => { const open = !header.classList.contains('is-open'); header.classList.toggle('is-open', open); toggle.setAttribute('aria-expanded', String(open)); toggle.setAttribute('aria-label', t(open ? 'navClose' : 'navOpen')); }); $$('.site-nav a').forEach(a => a.addEventListener('click', () => header?.classList.remove('is-open'))); const indicator = $('.nav-indicator'); function move(active){ if(!indicator || !active || innerWidth < 901) return; indicator.style.width = active.offsetWidth + 'px'; indicator.style.transform = 'translateX(' + active.offsetLeft + 'px)'; indicator.style.opacity = '1'; } const links = $$('.site-nav a'); links.forEach(a => a.addEventListener('mouseenter', () => move(a))); nav?.addEventListener('mouseleave', () => move($('.site-nav a.is-active') || links[0])); const sections = $$('.section-anchor'); const io = new IntersectionObserver(entries => { entries.forEach(entry => { if(entry.isIntersecting){ const id = entry.target.id; links.forEach(a => a.classList.toggle('is-active', a.getAttribute('href') === '#' + id)); move($('.site-nav a.is-active')); } }); }, { rootMargin:'-35% 0px -55% 0px', threshold:0 }); sections.forEach(s => io.observe(s)); setTimeout(() => move(links[0]), 80); }

  function initWorkCards(){ const root = $('[data-work-carousel]'); if(!root) return; const cards = $$('[data-work-card]', root); const dots = $$('[data-work-dot]', root); let index = 0; let startX = 0; let dragging = false; function render(next){ index = (next + cards.length) % cards.length; cards.forEach((card, i) => { const offset = (i - index + cards.length) % cards.length; card.classList.toggle('is-active', i === index); card.style.setProperty('--work-offset', offset); card.setAttribute('aria-hidden', String(i !== index)); }); dots.forEach((dot, i) => dot.classList.toggle('is-active', i === index)); } function step(delta){ render(index + delta); } $('[data-work-prev]', root)?.addEventListener('click', () => step(-1)); $('[data-work-next]', root)?.addEventListener('click', () => step(1)); dots.forEach(dot => dot.addEventListener('click', () => render(Number(dot.dataset.workDot || 0)))); root.addEventListener('keydown', ev => { if(ev.key === 'ArrowLeft'){ ev.preventDefault(); step(-1); } if(ev.key === 'ArrowRight'){ ev.preventDefault(); step(1); } }); root.addEventListener('pointerdown', ev => { dragging = true; startX = ev.clientX; root.setPointerCapture?.(ev.pointerId); }); root.addEventListener('pointerup', ev => { if(!dragging) return; dragging = false; const diff = ev.clientX - startX; if(Math.abs(diff) > 45) step(diff < 0 ? 1 : -1); }); root.addEventListener('pointercancel', () => { dragging = false; }); render(0); }
  function initVisuals(){ const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches; const io = new IntersectionObserver(entries => entries.forEach(e => { if(e.isIntersecting){ e.target.classList.add('is-visible'); io.unobserve(e.target); } }), { threshold:.12 }); $$('.reveal').forEach(el => io.observe(el)); $$('.spotlight-surface').forEach(card => card.addEventListener('pointermove', ev => { const r = card.getBoundingClientRect(); card.style.setProperty('--mx', ((ev.clientX-r.left)/r.width*100).toFixed(2)+'%'); card.style.setProperty('--my', ((ev.clientY-r.top)/r.height*100).toFixed(2)+'%'); })); if(!reduced){ addEventListener('scroll', () => { const device = $('[data-scroll-device]'); if(!device) return; const r = device.getBoundingClientRect(); const p = Math.max(-1, Math.min(1, (innerHeight/2 - (r.top+r.height/2)) / innerHeight)); device.style.setProperty('--device-y', (p*18).toFixed(1)+'px'); device.style.setProperty('--device-rx', (p*-5).toFixed(2)+'deg'); device.style.setProperty('--device-scale', String(1 + Math.abs(p)*.015)); }, { passive:true }); }
  }
  document.addEventListener('DOMContentLoaded', () => { document.body.classList.remove('is-loading'); initNav(); initForm(); initWorkCards(); initVisuals(); $$('[data-lang-option]').forEach(btn => btn.addEventListener('click', () => applyLanguage(btn.dataset.langOption))); $$('[data-case-tab]').forEach(btn => btn.addEventListener('click', () => renderCaseTab(btn.dataset.caseTab))); applyLanguage(state.lang); });
})();
