(() => {
  const instagramUrl = 'https://www.instagram.com/direct/t/andreyfabricio_';
  const instagramProfileUrl = 'https://www.instagram.com/andreyfabricio_/';
  const email = 'orcamento@andrey.systems'; // Operational contact email. Change here if the address is replaced later.
  const translations = {
    en: {
      navOpen:'Open menu',navClose:'Close menu',navHome:'Home',navFeatured:'ERP',navProjects:'Projects',navSolutions:'Solutions',navResults:'Results',navContact:'Contact',
      heroStatement:'Building digital solutions for real needs.',heroSpecialties:'Websites / Systems / Automation',exploreProjects:'Explore Projects',startProject:'Start a Project',heroLocation:'Based in Brazil / Working globally',
      featuredEyebrow:'Featured Project',featuredText:'A real management system built to centralize operational records, material control, budgets, work orders and reports.',challengeLabel:'Challenge',solutionLabel:'Solution',featuresLabel:'Features',resultLabel:'Result',viewFullCase:'View Full Case',
      projectsEyebrow:'Selected Projects',projectsTitle:'Projects with visual or functional proof.',projectErpType:'Client Project / Management System',projectErpText:'A custom system for internal operations, inventory, work orders, budgets, users, permissions, reports and backup.',viewProject:'View Project',projectImppelType:'Website Project',projectImppelText:'A business website direction for presenting services, credibility and contact paths with a cleaner digital presence.',projectSalvosType:'Personal Product / In Development',projectSalvosText:'A product in development used as a SaaS, routine and digital experience lab.',conceptType:'Website Concept',gymTitle:'Fitness / Gym Website',gymText:'A focused concept for classes, plans, schedules and lead capture.',churchTitle:'Church Website',churchText:'A community concept for events, ministries, agenda and communication.',constructionTitle:'Construction Business Website',constructionText:'A concept for technical services, proof of work and budget requests.',
      solutionsEyebrow:'Solutions',solutionsTitle:'What I can build.',solution1Title:'Business Websites',solution1Text:'Modern, responsive websites designed to communicate clearly and support business goals.',solution2Title:'Landing Pages',solution2Text:'Focused pages created to present an offer, guide attention and encourage action.',solution3Title:'Management Systems',solution3Text:'Custom tools designed to organize information, processes and daily operations.',solution4Title:'Portfolio Websites',solution4Text:'Professional digital spaces for individuals, creators and businesses.',solution5Title:'Automation',solution5Text:'Practical automations that reduce repetitive work and improve workflows.',solution6Title:'Custom Digital Products',solution6Text:'Solutions designed around the specific needs of each project.',
      workEyebrow:'How I Work',workTitle:'From problem to launch, in clear stages.',discoverTitle:'Discover',discoverText:'Understanding the business, the problem, the users and the desired outcome.',planTitle:'Plan',planText:'Defining scope, priorities, structure, references and the simplest effective solution.',buildTitle:'Build',buildText:'Designing, developing and validating each part of the project through clear stages.',launchTitle:'Launch',launchText:'Testing, refining, publishing and preparing the product for real use.',
      resultsEyebrow:'Built Outcomes',resultsTitle:'Concrete changes, without invented numbers.',erpBeforeAfter:'Manual records to centralized operation.',erpOutcome:'From disconnected controls to a structure for materials, inventory, work orders and reports.',siteBeforeAfter:'Limited presence to organized presentation.',siteOutcome:'A clearer visual path for services, proof and contact.',mobileOutcomeTitle:'Desktop and mobile as one product.',mobileOutcome:'Sections are designed to remain readable, useful and recordable on small screens.',workflowOutcomeTitle:'Scattered information to structured flow.',workflowOutcome:'Problems become screens, modules, actions and clear next steps.',
      contactEyebrow:'Contact',contactTitle:'Have an idea or a problem to solve?',contactText:"Let's build something useful.",labelName:'Name',labelCompany:'Company',labelContact:'Email or phone',labelType:'Project type',labelProblem:'Main current problem',labelTimeline:'Desired timeline',placeholderContact:'Email, WhatsApp or phone',placeholderProblem:'What needs to become clearer, faster or more organized?',placeholderTimeline:'This month, next quarter, no fixed deadline...',quoteReady:'Ready message to copy',copyMessage:'Copy message',copied:'Copied',formInstagram:'Open Instagram',formEmail:'Send by email',footerLine:'Andrey Fabricio / Digital Builder / Based in Brazil',rights:'All rights reserved.',
      caseHeroText:'A real system built for internal operations: CRM, budgets, work orders, materials, inventory, finance, after-sales, permissions and backup.',caseBack:'Back to Home',caseChallengeTitle:'Challenge',caseChallengeText:'The operation needed one reliable place to follow customers, budgets, service orders, material movement and responsibilities.',caseSolutionTitle:'Solution',caseSolutionText:'The ERP organizes the daily flow into connected modules with user roles, operational exports and technical backup.',caseFeaturesTitle:'What Exists',caseResultTitle:'Result',caseResultText:'The project became the main proof that Andrey Systems can turn an operational problem into a usable digital system.',caseCtaTitle:'Want a system or site with this level of care?',caseCtaText:'Send the project context and I will help define the simplest next step.'
    },
    pt: {
      navOpen:'Abrir menu',navClose:'Fechar menu',navHome:'Inicio',navFeatured:'ERP',navProjects:'Projetos',navSolutions:'Solucoes',navResults:'Resultados',navContact:'Contato',
      heroStatement:'Construindo solucoes digitais para necessidades reais.',heroSpecialties:'Sites / Sistemas / Automacao',exploreProjects:'Ver projetos',startProject:'Solicitar projeto',heroLocation:'Baseado no Brasil / Atendendo globalmente',
      featuredEyebrow:'Projeto em destaque',featuredText:'Um sistema real de gestao criado para centralizar registros operacionais, controle de materiais, orcamentos, ordens de servico e relatorios.',challengeLabel:'Desafio',solutionLabel:'Solucao',featuresLabel:'Recursos',resultLabel:'Resultado',viewFullCase:'Ver caso completo',
      projectsEyebrow:'Projetos selecionados',projectsTitle:'Projetos com prova visual ou funcional.',projectErpType:'Projeto real / Sistema de gestao',projectErpText:'Sistema personalizado para operacao interna, estoque, ordens de servico, orcamentos, usuarios, permissoes, relatorios e backup.',viewProject:'Ver projeto',projectImppelType:'Projeto de site',projectImppelText:'Direcao de site empresarial para apresentar servicos, credibilidade e caminhos de contato com uma presenca digital mais limpa.',projectSalvosType:'Produto proprio / Em desenvolvimento',projectSalvosText:'Produto em desenvolvimento usado como laboratorio de SaaS, rotina e experiencia digital.',conceptType:'Conceito de site',gymTitle:'Site para academia',gymText:'Conceito focado em aulas, planos, horarios e captacao de interessados.',churchTitle:'Site para igreja',churchText:'Conceito comunitario para eventos, ministerios, agenda e comunicacao.',constructionTitle:'Site para construtora ou prestadora',constructionText:'Conceito para servicos tecnicos, prova de trabalho e pedidos de orcamento.',
      solutionsEyebrow:'Solucoes',solutionsTitle:'O que posso construir.',solution1Title:'Sites empresariais',solution1Text:'Sites modernos e responsivos para comunicar com clareza e apoiar objetivos comerciais.',solution2Title:'Landing pages',solution2Text:'Paginas focadas para apresentar uma oferta, guiar a atencao e incentivar uma acao.',solution3Title:'Sistemas de gestao',solution3Text:'Ferramentas personalizadas para organizar informacoes, processos e rotinas operacionais.',solution4Title:'Portfolios digitais',solution4Text:'Espacos profissionais para pessoas, criadores e negocios.',solution5Title:'Automacao',solution5Text:'Automacoes praticas para reduzir trabalho repetitivo e melhorar fluxos.',solution6Title:'Produtos digitais sob medida',solution6Text:'Solucoes desenhadas em torno da necessidade especifica de cada projeto.',
      workEyebrow:'Como trabalho',workTitle:'Do problema ao lancamento, em etapas claras.',discoverTitle:'Descobrir',discoverText:'Entender o negocio, o problema, os usuarios e o resultado desejado.',planTitle:'Planejar',planText:'Definir escopo, prioridades, estrutura, referencias e a solucao simples mais eficaz.',buildTitle:'Construir',buildText:'Desenhar, desenvolver e validar cada parte do projeto por etapas claras.',launchTitle:'Lancar',launchText:'Testar, refinar, publicar e preparar o produto para uso real.',
      resultsEyebrow:'Resultados construidos',resultsTitle:'Mudancas concretas, sem numeros inventados.',erpBeforeAfter:'De registros manuais para operacao centralizada.',erpOutcome:'De controles desconectados para uma estrutura de materiais, estoque, ordens de servico e relatorios.',siteBeforeAfter:'De presenca limitada para apresentacao organizada.',siteOutcome:'Um caminho visual mais claro para servicos, provas e contato.',mobileOutcomeTitle:'Desktop e mobile como um unico produto.',mobileOutcome:'As secoes foram pensadas para continuar legiveis, uteis e gravaveis em telas pequenas.',workflowOutcomeTitle:'De informacao espalhada para fluxo estruturado.',workflowOutcome:'Problemas viram telas, modulos, acoes e proximos passos claros.',
      contactEyebrow:'Contato',contactTitle:'Tem uma ideia ou problema para resolver?',contactText:'Vamos construir algo util.',labelName:'Nome',labelCompany:'Empresa',labelContact:'E-mail ou telefone',labelType:'Tipo de projeto',labelProblem:'Principal problema atual',labelTimeline:'Prazo desejado',placeholderContact:'E-mail, WhatsApp ou telefone',placeholderProblem:'O que precisa ficar mais claro, rapido ou organizado?',placeholderTimeline:'Este mes, proximo trimestre, sem prazo fixo...',quoteReady:'Mensagem pronta para copiar',copyMessage:'Copiar mensagem',copied:'Copiada',formInstagram:'Abrir Instagram',formEmail:'Enviar por e-mail',footerLine:'Andrey Fabricio / Digital Builder / Baseado no Brasil',rights:'Todos os direitos reservados.',
      caseHeroText:'Sistema real criado para operacao interna: CRM, orcamentos, ordens de servico, materiais, estoque, financeiro, pos-venda, permissoes e backup.',caseBack:'Voltar para Home',caseChallengeTitle:'Desafio',caseChallengeText:'A operacao precisava de um lugar confiavel para acompanhar clientes, orcamentos, ordens de servico, movimentacao de materiais e responsabilidades.',caseSolutionTitle:'Solucao',caseSolutionText:'O ERP organiza a rotina em modulos conectados com perfis de usuario, exportacoes operacionais e backup tecnico.',caseFeaturesTitle:'O que existe',caseResultTitle:'Resultado',caseResultText:'O projeto virou a principal prova de que a Andrey Systems consegue transformar um problema operacional em um sistema digital utilizavel.',caseCtaTitle:'Quer um sistema ou site com esse nivel de cuidado?',caseCtaText:'Envie o contexto do projeto e eu ajudo a definir o proximo passo mais simples.'
    }
  };
  const caseTabs = {
    en:{challenge:['Operational information was scattered.','Important records lived across manual controls and disconnected routines, making it harder to follow work orders, material movement, budgets and internal responsibilities from one place.'],solution:['A real ERP for daily operations.','The system centralizes CRM, budgets, work orders, materials, stock, finance, warranties, role permissions and backup routines in one operational environment.'],features:['Modules built around real routines.','CRM, budgets, service orders, material control, inventory, finance, warranties, after-sales, permissions by role, backup and restoration.'],result:['Proof through a working product.','The ERP IMPPEL shows a complete operational system without promising invented financial metrics: the proof is the structure, screens and implemented flow.']},
    pt:{challenge:['Informacoes operacionais estavam espalhadas.','Registros importantes ficavam em controles manuais e rotinas desconectadas, dificultando acompanhar ordens de servico, materiais, orcamentos e responsabilidades em um unico lugar.'],solution:['Um ERP real para a rotina diaria.','O sistema centraliza CRM, orcamentos, ordens de servico, materiais, estoque, financeiro, garantias, permissoes por cargo e rotinas de backup em um ambiente operacional.'],features:['Modulos criados em torno da rotina real.','CRM, orcamentos, ordens de servico, controle de materiais, estoque, financeiro, garantias, pos-venda, permissoes por cargo, backup e restauracao.'],result:['Prova por produto funcionando.','O ERP IMPPEL mostra um sistema operacional completo sem prometer metricas financeiras inventadas: a prova esta na estrutura, nas telas e no fluxo implementado.']}
  };
  const state = { lang: localStorage.getItem('andrey-lang') || 'en' };
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  function t(key){ return (translations[state.lang] && translations[state.lang][key]) || translations.en[key] || key; }
  function applyLanguage(lang){ state.lang = translations[lang] ? lang : 'en'; localStorage.setItem('andrey-lang', state.lang); document.documentElement.lang = state.lang === 'pt' ? 'pt-BR' : 'en'; $$('[data-i18n]').forEach(el => { el.textContent = t(el.dataset.i18n); }); $$('[data-i18n-placeholder]').forEach(el => { el.placeholder = t(el.dataset.i18nPlaceholder); }); $$('[data-i18n-aria-label]').forEach(el => { el.setAttribute('aria-label', t(el.dataset.i18nAriaLabel)); }); $$('[data-lang-option]').forEach(btn => btn.classList.toggle('is-active', btn.dataset.langOption === state.lang)); renderCaseTab($('.tab-button.is-active')?.dataset.caseTab || 'challenge'); updateQuote(); }
  function renderCaseTab(tab){ const panel = $('[data-case-panel]'); if(!panel) return; const data = (caseTabs[state.lang] || caseTabs.en)[tab] || caseTabs[state.lang].challenge; panel.querySelector('h3').textContent = data[0]; panel.querySelector('p').textContent = data[1]; $$('[data-case-tab]').forEach(btn => { const active = btn.dataset.caseTab === tab; btn.classList.toggle('is-active', active); btn.setAttribute('aria-selected', String(active)); }); }
  function quoteMessage(){ const form = $('#quote'); if(!form) return ''; const data = new FormData(form); const pt = state.lang === 'pt'; const lines = pt ? ['Ola, Andrey! Quero conversar sobre um projeto.','','Nome: '+(data.get('nome')||''),'Empresa: '+(data.get('empresa')||''),'Contato: '+(data.get('contato')||''),'Tipo de projeto: '+(data.get('tipo')||''),'Problema atual: '+(data.get('problema')||''),'Prazo desejado: '+(data.get('prazo')||''),'','Vi seu site da Andrey Systems e gostaria de um direcionamento.'] : ['Hi, Andrey! I want to talk about a project.','','Name: '+(data.get('nome')||''),'Company: '+(data.get('empresa')||''),'Contact: '+(data.get('contato')||''),'Project type: '+(data.get('tipo')||''),'Current problem: '+(data.get('problema')||''),'Desired timeline: '+(data.get('prazo')||''),'','I saw your Andrey Systems website and would like some direction.']; return lines.join('\\n'); }
  function updateQuote(){ const form = $('#quote'); if(!form) return; const message = quoteMessage(); const box = $('#quoteMessage'); const text = $('#quoteMessageText'); const link = $('#quoteEmailLink'); if(text) text.textContent = message; if(box) box.hidden = !message.trim().replace(/[^A-Za-z0-9]/g,''); if(link){ const subject = state.lang === 'pt' ? 'Solicitacao de projeto - Andrey Systems' : 'Project request - Andrey Systems'; link.href = 'mailto:' + email + '?subject=' + encodeURIComponent(subject) + '&body=' + encodeURIComponent(message); } }
  function initForm(){ const form = $('#quote'); if(!form) return; form.addEventListener('input', updateQuote); form.addEventListener('change', updateQuote); form.addEventListener('submit', (ev) => { ev.preventDefault(); updateQuote(); window.open(instagramUrl, '_blank', 'noopener,noreferrer') || window.open(instagramProfileUrl, '_blank', 'noopener,noreferrer'); }); $('#quoteCopyButton')?.addEventListener('click', async () => { const msg = quoteMessage(); try { await navigator.clipboard.writeText(msg); $('#quoteCopyButton').textContent = t('copied'); setTimeout(() => $('#quoteCopyButton').textContent = t('copyMessage'), 1400); } catch { $('#quoteMessageText')?.focus(); } }); updateQuote(); }
  function initNav(){ const header = $('[data-header]'); const toggle = $('.nav-toggle'); const nav = $('.site-nav'); toggle?.addEventListener('click', () => { const open = !header.classList.contains('is-open'); header.classList.toggle('is-open', open); toggle.setAttribute('aria-expanded', String(open)); toggle.setAttribute('aria-label', t(open ? 'navClose' : 'navOpen')); }); $$('.site-nav a').forEach(a => a.addEventListener('click', () => header?.classList.remove('is-open'))); const indicator = $('.nav-indicator'); function move(active){ if(!indicator || !active || innerWidth < 901) return; indicator.style.width = active.offsetWidth + 'px'; indicator.style.transform = 'translateX(' + active.offsetLeft + 'px)'; indicator.style.opacity = '1'; } const links = $$('.site-nav a'); links.forEach(a => a.addEventListener('mouseenter', () => move(a))); nav?.addEventListener('mouseleave', () => move($('.site-nav a.is-active') || links[0])); const sections = $$('.section-anchor'); const io = new IntersectionObserver(entries => { entries.forEach(entry => { if(entry.isIntersecting){ const id = entry.target.id; links.forEach(a => a.classList.toggle('is-active', a.getAttribute('href') === '#' + id)); move($('.site-nav a.is-active')); } }); }, { rootMargin:'-35% 0px -55% 0px', threshold:0 }); sections.forEach(s => io.observe(s)); setTimeout(() => move(links[0]), 80); }
  function initVisuals(){ const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches; const io = new IntersectionObserver(entries => entries.forEach(e => { if(e.isIntersecting){ e.target.classList.add('is-visible'); io.unobserve(e.target); } }), { threshold:.12 }); $$('.reveal').forEach(el => io.observe(el)); $$('.spotlight-surface').forEach(card => card.addEventListener('pointermove', ev => { const r = card.getBoundingClientRect(); card.style.setProperty('--mx', ((ev.clientX-r.left)/r.width*100).toFixed(2)+'%'); card.style.setProperty('--my', ((ev.clientY-r.top)/r.height*100).toFixed(2)+'%'); })); if(!reduced){ addEventListener('scroll', () => { const device = $('[data-scroll-device]'); if(!device) return; const r = device.getBoundingClientRect(); const p = Math.max(-1, Math.min(1, (innerHeight/2 - (r.top+r.height/2)) / innerHeight)); device.style.setProperty('--device-y', (p*18).toFixed(1)+'px'); device.style.setProperty('--device-rx', (p*-5).toFixed(2)+'deg'); device.style.setProperty('--device-scale', String(1 + Math.abs(p)*.015)); }, { passive:true }); }
  }
  document.addEventListener('DOMContentLoaded', () => { document.body.classList.remove('is-loading'); initNav(); initForm(); initVisuals(); $$('[data-lang-option]').forEach(btn => btn.addEventListener('click', () => applyLanguage(btn.dataset.langOption))); $$('[data-case-tab]').forEach(btn => btn.addEventListener('click', () => renderCaseTab(btn.dataset.caseTab))); applyLanguage(state.lang); });
})();
